name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    name: Build and deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/hello-world:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region eu-central-1 \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy with Helm
        run: |
          helm upgrade \
            --install \
            --namespace hello-world \
            --create-namespace \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/hello-world \
            --set image.tag=${{ github.sha }} \
            hello-world \
            ./chart
