name: Checks

on:
  # Run on all PRs
  pull_request:
  # It should also be possible to run all checks manually
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Check files with Super-Linter
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          VALIDATE_PYTHON_PYLINT: false # Disable in favor of ruff and friends
          VALIDATE_TERRAFORM_TERRASCAN: false # until https://github.com/tenable/terrascan/issues/1390 is fixed
          VALIDATE_KUBERNETES_KUBECONFORM: false # breaks on Helm templates
          VALIDATE_YAML: false # yamllint breaks on Helm templates
